variables:
  REGISTRY: "image-registry.openshift-image-registry.svc:5000"
  NAMESPACE: 'java-school'
  APP_NAME: "eureka-server"
  APP_IMAGE: "$REGISTRY/$NAMESPACE/$APP_NAME"
  TEMP_IMAGE_TAG: "temp_$CI_PIPELINE_ID"
  KUBERNETES_CPU_REQUEST: '1'
  KUBERNETES_CPU_LIMIT: '1'
  KUBERNETES_MEMORY_REQUEST: '1Gi'
  KUBERNETES_MEMORY_LIMIT: '1Gi'

image: "$REGISTRY/openshift/cli:latest"

stages:
  - build
  - docker_build
  - deploy
  - clean

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build-eureka:
  image: bellsoft/liberica-openjdk-alpine:11.0.11
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - chmod +x gradlew
    - gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  only:
    - gitlab_ci_services
  tags:
    - java_school

docker_build-eureka:
  variables:
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: 'builder'
  stage: docker_build
  image:
    name: $REGISTRY/openshift/kaniko:openshift
  script:
    - cat /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt >> $SSL_CERT_DIR/ca-certificates.crt
    - echo "{\"auths\":{\"$REGISTRY\":{\"username\":\"serviceaccount\",\"password\":\"$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\"}}}" > $DOCKER_CONFIG/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/test_service --dockerfile $CI_PROJECT_DIR/test_service/Dockerfile --destination $APP_IMAGE:$TEMP_IMAGE_TAG --cache=true --cache-repo ${APP_IMAGE}-cache
  only:
    - gitlab_ci_services
  tags:
    - java_school

deploy_staging-eureka:
  stage: deploy
  script:
    - oc tag $NAMESPACE/$APP_NAME:$TEMP_IMAGE_TAG $NAMESPACE/$APP_NAME:latest
  only:
    - gitlab_ci_services
  tags:
    - java_school

clean-eureka:
  stage: clean
  script:
    - oc delete istag/$APP_NAME:$TEMP_IMAGE_TAG -n $NAMESPACE
  tags:
    - java_school
  only:
    - gitlab_ci_services
  when: always
