# Слава, проверь все!
eureka:
  instance:
    hostname: eureka-server-java-school.apps.okd.stage.digital.rt.ru
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka/

