application:
  url: http://localhost:${server.port}${server.servlet.context-path}

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

resource-server:
  api:
    url: http://localhost:8080/resource-server/api/music

